services:
   web:
     image: nginx:stable-bookworm
     container_name: nginx
     ports:
       - "9090:90"
     volumes:
       - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
   app:
     build:
       context: ./backend/php
     container_name: php-fpm
     volumes:
       - ./backend/src:/var/www/app
   db:
    image: mysql:8.0
    container_name: db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 6606:3306
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: true
       MYSQL_DATABASE: todos
       LANG: C.UTF-8
volumes:
  mysql: